spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: //TODO
    username: //TODO
    password: //TODO
    driver-class-name: org.postgresql.Driver
